pipeline {
  agent {
    docker { image 'node:14' }
  }
  environment {
    HOME = '.'
  }
  stages {
    stage('Install') {
      steps {
        dir(path: 'back') {
          sh 'npm install'
        }
      }
    }
    stage('Test') {
      steps {
        dir(path: 'back') {
          sh 'npm run coverage'
        }
      }
    }
  }
}