pipeline {
  agent {
    docker { image 'node:14' }
  }
  stages {
    stage('build') {
      steps {
        dir(path: 'back') {
          sh 'npm npm i'
          sh 'npm run coverage'
        }
      }
    }
  }
}