pipeline {
  agent {
    label 'master'
  }
  stages {
    stage('Install') {
      steps {
        dir(path: 'front') {
          sh 'npm install'
        }
      }
    }
    stage('Test') {
      steps {
        dir(path: 'front') {
          sh 'npm run coverage'
        }
      }
    }
    stage('Publish Reports') {
          environment {
            CODECOV_TOKEN = credentials('codecov_token')
          }
          steps {
            dir(path: 'back') {
              sh 'curl -s https://codecov.io/bash | bash -s - -t $CODECOV_TOKEN'
            }
          }
    }
  }
  environment {
    HOME = '.'
  }
}