name: Backend

on:
  push:
    branches:
    - master
    - ts
    - 'back/**'

  pull_request:
    branches:
    - master
    - ts

defaults:
  run:
    working-directory: ./back

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: '~/.npm'
        key: ${{ runner.os }}-back-${{ hashFiles('**/package-lock.json') }}
    
    - name: Install dependencies
      run: npm ci

    - name: Run tests  & coverage
      run: npm run coverage

    - name: Publish coverage
      run: curl -s https://codecov.io/bash | bash -s - -t ${{ secrets.CODECOV_TOKEN }}

  Publish:
    runs-on: ubuntu-latest
    needs: Test
    if: github.ref == 'refs/heads/ts'

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./back/Dockerfile
        push: true
        tags: axbg/cyberbox-back:latest
